define emrach = Character("Эмрах", color="#fff")
define companyDirector = Character("Сергей Геннадьевич", color="#fff")
define spaghettinio = Character("Спагеттиньо", color="#fff")
define bagio = Character("Баггио", color="#fff")
define numbertaurus = Character("Цифротаурус", color="#fff")
define aught = Character("Нечто", color="#fff")
define security = Character("Охраник", color="#fff")
define vetrorosa = Character("Система безопасности мояка \"Ветророза\"", color="#fff")