image bg bagio = "images/bagio.png"
image bg directorOffice = "images/directorOffice.png"
image bg emrach = "images/emrach.png"
image bg spaghettinio = "images/spaghettinio.png"
image bg temporaryRadik = "images/temporaryRadik.png"